\title{
Saad Mufti
}

Alpharetta, GA 30005 | (508)-361-8811 | smufti3@gatech.edu | U.S. Citizen

linkedin.com/in/saad-mufti-662b2918b | github.com/Saad-Mufti | stackoverflow.com/users/13351293

\section*{Objective}

Computer fanatic with an appetite for hard problems. Highly adaptive, stress tolerant. Diverse background in embedded/web/cloud software development, ML applications. Interest in silicon engineering, RTL design, reinforcement learning.

\section*{Education}

Georgia Institute of Technology | Atlanta, GA

Bachelor of Science in Computer Engineering, GPA 4.0

Worcester Polytechnic Institute | Worcester, MA

Transfer with 90 Credit Hours, GPA 4.0 / 4.0
Aug 2022 - Present

Expected Graduation (After MS): May 2025

Aug 2021 - Jun 2022

\section*{Skills}

Programming: Python, C/C++, SystemVerilog/Verilog/VHDL, Tcl, JavaScript/Node.js, MATLAB, Java, SQL, Swift, Kotlin

Platforms: RISC-V, Intel x86, AWS (EC2, Load Balancing), GCP (Cloud Run, Firebase, Cloud Functions, App Engine)

Hardware: Nvidia Jetson, Raspberry Pi, ARM mbed microcontroller, FPGAs, oscilloscope, logic analyzer, TI MSP430, Arduino

Software: Vivado, Altera Quartus, PyTorch/Tensorflow, Synopsys VCS/DVE, Docker, Cadence Virtuoso, Android Studio, Git, Flask

\section*{Experience}

Georgia Tech | Atlanta, GA

RISC-V Processor Design + Tapeout

Aug 2023 - May 2024

- Design and verification of an SoC including RISC-V processor, UART, SPI, CORDIC modules, using $65 \mathrm{~nm}$ TSMC PDK.

- Theory, design, verification, test of fabricated synchronous CMOS digital circuit. Using synthesis, autoplace and route (SAPR) as industry standard tools.

Tektronix Inc. | Beaverton, OR

Jun - Aug 2023

Applications Engineering Intern

- Researched and validated a framework (using mmWave FMCW + CNNs) for federated learning on beam prediction using low power devices (Nvidia Jetson) for test + measurement.

- Optimized training routine (in PyTorch) to accommodate resource constrained devices, enabling inspection of model performance relating to different layer types, using GPU acceleration (CUDA + TensorRT).

- Identified possible solutions to improve model accuracy and performance, increasing model metrics by $5-10 \%$ with $20 \%$ smaller memory footprint.

- Helped pitch solution for object tracking using Bispectral NNs (Sanborn, 2023), flexible replacement over conventional FFT.

Yousefi Lab @ WPI | Worcester, MA

Reinforcement Learning and Data Pipeline Researcher

Jun-Aug 2022

- Researched and validated a reinforcement learning model that fit design requirements, assisted in its development using TensorFlow, producing a proof-of-concept.

- Orchestrated development of a data pipeline using GCP tools (Pub/Sub, Dataflow, BigQuery, Vertex Al) to ingest, preprocess, and store neural data for training and running inference on a developed RL model, demonstrating scalability.

Shoptaki Inc. I New York City, NY (Remote)

Aug 2021 - Aug 2022

Fullstack Engineer (Began as SWE Intern)

- Led full-stack (frontend + backend) development of a demo website for newcomers in data science, using ReactJS, Flask, Express, and Arango DB.

- Implemented CD pipelines in various development workflows using GitHub Actions and GCP Cloud Run/Build, reducing errors in manual deployment to $<5 \%$ of deployments.

- Assisted cloud migration of various AWS services to GCP with minimal impact on service or user experience.

\section*{Relevant Coursework}

Data Structures + Analysis of Algorithms: Implementing and evaluating time complexity of arrays, Binary Search Trees (BSTs), Linked Lists, stacks, graph algorithms, searching/sorting, Dynamic programming, NP-Completeness, Linear Programming, Cryptography. Machine Learning (WPI, Graduate Level): Markov Chains, Maximum Likelihood Estimation, Graphical Models, Gaussian Processes, Neural Networks, Reinforcement Learning, and building a deep mathematical foundation to understand them.