- Relevant Coursework: Data Structures and Algorithms, Design \& Analysis of Algorithms, Intro to AI, Digital Design Lab, Machine Learning, Operating Systems

Skills, LANGUAGES, AND AwARdS

Programming Languages: Java, HTML/CSS, JavaScript, C, VHDL, Python, Kotlin, PostgreSQL

Frameworks: React, Angular, Flutter

Certifications:

Oracle Certified Associate, Java SE 8 Programmer

Awards:

NJIT Programming Competition(1st in GSU)

Honors:

MLT CP Fellow, KP Fellow Finalist

WORK EXPERIENCE

Systems Engineering Intern

Boston Scientific / Valencia, CA

May 2023 - Aug 2023

- Pioneered the development of a POC desktop and mobile application with Flutter, enabling real-time battery estimates for over 2,000 devices aiding patients with chronic pain and Parkinson's

- Coordinated UI design through Figjam and Figma, garnering positive feedback from 3 marketing teams and $2 \mathrm{PMs}$

- Automated a script to streamline device programming, slashing therapy programming time by an impressive $93 \%$

Software Engineering Intern

Jan 2023 - May 2023

AudioT / Atlanta, GA

- Engineered a desktop tool, utilized by 15 team members, that reduced human error by $20 \%$ in training a poultry health identification model

- Employed React, Amazon S3, AWS Lambda, and PostgreSQL to construct a data schema for an application handling over 50,000 records

Software Development Intern

May 2022 - Aug 2022

Amazon / Seattle, WA

- Revitalized an internal web-based tool, elevating efficiency in tax document automation by $63 \%$, which benefitted $40+$ financial analysts

- Spearheaded the creation and testing of AWS Lambda functions, seamlessly integrating them with Amazon API Gateway and Cloud Formation

Software Engineering Intern (STEP)

Google / Remote

May 2021 - Aug 2021

- Overhauled a financial dashboard that facilitated over $\$ 3$ trillion in transactions, improving productivity by $30 \%$

- Mitigated technical debt by identifying and rectifying 17 critical bugs, resulting in a $15 \%$ increase in codebase efficiency

LEADERSHIP

Founding Secretary

GSU ProgClub

Sept 2020 - May 2021

- Quadrupled club membership to $400+$ through targeted events like hackjams, speaker series, and interview prep sessions

- Launched bi-weekly technical mock interview sessions, boosting participant confidence levels by an average of $25 \%$

- Conducted weekly coding workshops, resulting in a $20 \%$ increase in member engagement and practical skill development