\title{
Azeez Ishaqui
}

- Gmail — azishaqui@gmail.com $・$ LinkedIn $\cdot$678-313-6772 $\cdot$ U.S. Citizen

\section*{EDUCATION}

Georgia Institute of Technology - Atlanta, GA

M.S. in Machine Learning, Current Masters student, BS/MS program — GPA: 4.0/4.0

Georgia Institute of Technology - Atlanta, GA

B.S. in Computer Science (Artificial Intelligence) — GPA: 4.0/4.0

Technical Skills: Python, PyTorch, Java, C/C++, Scala, AWS (EC2/STS), Terraform, Docker, SQL, HTML/JS/CSS, Assembly

Languages: French (Advanced), English (Native)

Relevant Coursework: Machine Learning, Deep Learning, Software Development, Data Structures and Design/Analysis of Algorithms, Probability/Statistics, Linear Algebra, Combinatorics, Discrete Mathematics, Multivariable Calculus, Introductory AI

\section*{WORK EXPERIENCE}

KPMG CIO Advisory

June 2023 - August 2023

- Constructed an AI chatbot with full-stack skills including HTML/JS/CSS embedded onto Unqork to manage client database

- Leveraged ML tools like Scikit, NumPy, and Pandas to improve Great American Health user experience and customer retention

- Implemented a scalable deployment of the chatbot with a Flask API using NGINX reverse proxy and Gunicorn on an $\underline{\text { AWS }}$ EC2 instance, integrated with OpenAI GPT-3 chat functionality on a secure environment with proper user access control

- Conducted data analysis, prepared reports, and utilized Excel and data visualization tools to assist executive decision-making

- Analyzed comprehensive migration strategies and roadmaps, including assessment of on-premises healthcare infrastructure, application analysis, and cost optimization plans, resulting in efficient and cost-effective cloud deployments within $\underline{\text { GCP }}$

ASI (Aggregate Singularity Industries) Cloud/Devops Engineer

June 2022 - August 2022

- Developed cloud-based AWS services, API integrations with Snyk for compromised repositories security, bucket pruning for performance/cost optimization, and an EC2 discovery service with instance tagging and Prometheus scrape configuration

- Created a Slack-integrated service for company website traffic monitoring, containerized on Docker, configured with $\underline{\text { Grafana }}$ and Prometheus to initiate error threshold alerting for company-wide server maintenance, critical for users and employees alike

- Provisioned and managed resources on Terraform, including load balancers, access keys, and customized port configurations for efficient traffic handling, while maintaining domain server privacy for developers

- Utilized EC2/STS services and Terraform resource provisioning to administer an AWS replication service that safeguarded server functionality during internal network failures and complete outages

Assurant Inc. Team Project Lead \& ML System Designer

January 2023 - Present

- Automated data ingestion scraping FRED macro-economics handled on Python for a housing price prediction model with metro-Atlanta data with pre-processing techniques and supervised learning including multivariate time-series analysis and $\underline{\mathbf{K}-}$ nearest neighbors to minimize loss and reduce overfitting

- Designed and co-implemented an $\underline{\text { ML pipeline with Assurant engineers focusing on precision and efficiency within AWS }}$

Cognira (Retail/Analytics Software Company) Software Development Intern

June 2021 - August 2021

- Administered a web server which ingested client data and performed several forms of data optimization analysis using Scala

- Performed server testing using an external software client and Docker containers for application isolation and portability

Eye Consultants of Atlanta Data Analytics Intern - Eye Consultants of Atlanta

January 2021 - February 2021

\section*{LEADERSHIP/PUBLICATIONS}

Founder of "Charity 4 All", a non-profit organization - Charity 4 All Solo Project

March 2017 - Present

- Publications: Atlanta Journal Constitution - $\underline{\mathrm{AJC}}$

- Fundraised over $\$ 2500$ through GoFundMe, leveraged social media and personal network to spread awareness of the nonprofit, used surplus money raised to provide pencils, notebooks, textbooks, to support over twenty students' education

- Facilitated international logistics to ship and hand-deliver 2000+ masks to several different Atlanta Homeless Shelters

- Invigorated local economy by providing carts and sewing machines to needy vendors and widows, annually distributed food staples and durable goods during Ramadan to impoverished families with limited access after fasting