\title{
Daniyal Hussain
}

New York, NY | 347-658-6214 | dh3144@nyu.edu |

www.daniy.al | linkedin.com/in/hussain-daniyal/ | github.com/tuffstuff9 |

EDUCATION

New York University, College of Arts and Sciences, New York, NY

Bachelor of Arts in Computer Science and Data Science

Graduated: May 2023

Cumulative GPA: 3.5

Technical Skills

Languages: TypeScript, JavaScript, C\#, Java, Python, R, HTML/CSS, SQL

Frameworks/Technologies: React, Next.js, PlanetScale, TensorFlow, PyTorch, Hadoop, Maven, WinUI 3, Git, Jira, Figma, REST API, Postman, Node.js, Agile/Scrum, AWS, Azure, Google Cloud, Jest, Mocha, Chai, Docker

\section*{Professional Experience}

Deloitte

June 2022 - August 2022

Software Engineer Intern

Remote

- Engineered SPA and SQL database for Ministry of Mining's user/business accounts with robust authentication

- Implemented page wireframes by designing front-end using JavaScript and OutSystems with optimized UX

- Delivered functional prototypes to enable client evaluations and feedback on user experience and design aspects

Berry Mount

June 2021 - January 2022

Software Engineer

Remote

- Overhauled company ERP and CRM software from excel spreadsheet/FocusERP hybrid-system to Odoo software

- Automated and trained team on invoice tracking, payment deposits, inventory management, vendor/client reports

- Integrated missing invoice tracker and mitigated inventory loss, restoring $\$ 4,000-\$ 10,000$ in business transactions

USME Supply Lines Trading

June 2020 - August 2020

Business Analyst Intern

Los Angeles, CA

- Constructed an internal program to produce pricing quotes, increasing quote frequency from weekly to biweekly

- Sourced new freight partners to reduce shipment costs, increasing weekly operational profitability by $\$ 1,000-\$ 3,000$

- Conducted cost-benefit analyses for business expansion, leading to the successful launch of two new products

University of California Los Angeles $\quad$ June 2018 - July 2018

Research Assistant

Los Angeles, $C A$

- Streamlined manual data retrieval process from NIST to study effects of cryogenic cooling on hydrogen fuel

- Scraped database using Python and VBA with variable input parameters to generate error reports for models

Projects

wandy.ai - SaaS AI Model Tuner | TypeScript, React, Next.js, ClerkJS, PlanetScale, Drizzle, Zod, Stripe

- Engineered full-stack solution for real-time AI model tuning \& comparison, prompt generator, and training on documents

SlideResume.com - SaaS cover letter generator | TypeScript, React, Next.js, ClerkJS, PlanetScale, Drizzle, Zod, Stripe

- Produced a user-centric SaaS web app which automates personalized cover letter generation from uploaded resume

Leetcode AI Assistant - Chrome Extension | JavaScript, React, Chrome MV3

- Designed and built a Chrome extension which acts as an automated flashcard system for LeetCode, with AI assistance

- Leveraged latest Chrome APIs (MV3) to incorporate efficient DOM manipulation and optimize performance

KeyboardHookLite $\mid$ C\#

- Developed a low-level keyboard hook library for modern UI frameworks, with unmanaged code disposal

- Published on Nuget with over $3000+$ user downloads and on GitHub with detailed documentation

NYU Course Tracker | JavaScript, Puppeteer, Telegram

- Utilized headless browser to scrape NYU course status and alert users in real-time for their class openings

- Bypassed session expiry using stealth features to avoid detection by randomly manipulating user agent

Other Projects: nextjs-pdf-parser, PlanetScale + Drizzle Boilerplate, OCR AI Assistant (Chrome Extension), Visualizer.coffee Shot Downloader (Website Scraper), ChatGPT Clipper (Chrome Extension), React Blackjack (Web App)