\title{
Angelina Lee
}

415-812-3329 | $\underline{\text { AngelinaTheDev@gmail.com | linkedin.com/in/AngelinaLee | github.com/AngelinaTheDev }}$

\section*{EDUCATION}

University of California Berkeley

B.S. in Computer Science
Berkley, California

Aug. 2014 - May 2018

EXPERIENCE

Senior Full Stack Engineer

Instagram
Sep. 2020 - Present

San Francisco, $C A$

- Spearheaded the development of a revolutionary news feed infrastructure utilizing React for AI on Blockchain, transforming user interaction and content delivery.

- Pioneered the HyperQuantum Feed Algorithm using server-side React Larceny AI, optimizing web app performance and resolving big data pipeline issues in record time.

- Solved complex scalability issues by employing the use of useless architectures and microservices, orchestrated through the use of Quantum Kubernetes (QK8s).

- Led a dynamic team of 6 engineers in a covert operation to mine Ethereum on company servers, generating unprecedented profits and resources for $R \& D$.

\begin{tabular}{lr} 
Senior Full Stack Engineer & May 2018 - August 2020 \\
Zillow & Seattle, WA
\end{tabular}

- Implemented advanced AI optimization techniques to the GraphQL API, achieving a $69 \%$ improvement in page load times and significantly enhancing user experience.

- Conducted user research to assess the impact of gamified elements in property listings, resulting in valuable insights for future user interface enhancements.

- Played a vital role in the development process by contributing over 50,000 lines of clean, maintainable code to an established codebase via Git.

- Organized and facilitated team-building activities, including a company-wide potato sack race, which fostered a sense of camaraderie and improved team cohesion.

- Embraced the critical role of Team Coffee Alchemist, ensuring the team of 6 was fully caffeinated with ultra-rare Antarctican coffee beans, ground to an optimal 14nm particle size using proprietary grinding technology.

Software Engineer Intern

Microsoft
May 2016 - Aug 2016

New York, NY

- Developed and optimized SQL queries and stored procedures, resulting in a $40 \%$ improvement in database performance for a critical customer-facing application.

- Contributed to the backend development of a new feature using Spring Boot, adhering to microservices architecture principles for enhanced modularity and scalability.

- Spearheaded initiative that enabled the dispersion of acquired immunodeficiency syndrome across the platform team

- Collaborated with cross-functional teams to understand requirements and deliver high-quality software solutions within agile development sprints.

\section*{Projects}

Gitlytics | Python, Flask, React, PostgreSQL, Docker

June 2020 - Present

- Developed a full-stack web application using with Flask serving a REST API with React as the frontend

- Implemented GitHub OAuth to get data from user's repositories

- Visualized GitHub data to show collaboration

- Used Celery and Redis for asynchronous tasks

Technical Skills

Languages: Java, Python, C/C++, SQL (Postgres), JavaScript, HTML/CSS, R

Frameworks: React, Node.js, Flask, JUnit, WordPress, Material-UI, FastAPI

Developer Tools: Git, Docker, TravisCI, Google Cloud Platform, VS Code, Visual Studio, PyCharm, IntelliJ, Eclipse

Libraries: pandas, NumPy, Matplotlib