\title{
Zeyad Al Sakhi
}

( github.com/zeyadtmi | in linkedin.com/in/zeyadalsakhi | $\boldsymbol{\text { zsakhi3@gatech.edu | }}$ +1 4049553707| Atlanta, GA EDUCATION

Georgia Institute of Technology

B.S. Computer Science - Bahrain Crown Prince International Scholarship

Aug 2021 - May 2024

Concentrations: Computer Systems Architecture and Information Internetworks

TeChnical Skills

Software languages: $\mathrm{C}, \mathrm{C}++$, Python, Java, Assembly, VHDL

Web Technologies: React, HTML, CSS, JavaScript

ML/AI: Numpy, Pandas, ScikitLearn, Matplotlib

Other: MySQL, Git, LateX, Android Studio, Agile, Jira

Relevant Coursework: Advanced Computer Architecture, Processor Design, Operating Systems, Machine Learning, Artificial Intelligence, Advanced Algorithms and Data Structures, Networking, OOP, Algorithmic Design, Databases

EXPERIENCE

Investcorp

Security Engineer

June 2023 - August 2023

Bahrain

- Developed an Outlook Metadata Anomaly Detector using Azure Synapse Analytics and PySpark for data processing and analysis, flagging suspicious email activities.

- Analyzed 500,000+ email meta entries, identifying $0.2 \%$ as potential threats based on features like excessive BCC to external domains, irregular email timings, and unusual recipient interactions.

- Conducted broad scanning and vulnerability analysis, investigating source and destination IPs and port numbers, improving vulnerability detection by $25 \%$ and enhancing network security.

- Designed a Ransomware Incident Handling Playbook, outlining procedural guidelines and response strategies to efficiently address potential ransomware attacks, reducing response time by $40 \%$.

Bapco Energies

May 2023 - June 2023

Cyber Security Trainee

Awali, Southern Governorate, Bahrain

- Managed SOC incident handling using Microsoft Sentinel and Microsoft Defender Security, streamlining threat detection and mitigation processes, resulting in a $20 \%$ faster response to incidents.

- Developed a web scraper to extract security-related keywords from Google articles, enhancing employee awareness and reducing security-related incidents by $15 \%$.

- Employed Azure Sentinel and KQL for real-time data extraction and analysis from security logs, enabling prompt threat detection and response, analyzing 100+ events daily.

Georgia Tech Vertically Integrated Program

Machine Learning Research Team Lead

Aug 2022 - Present

Atlanta, Georgia

- Led the largest research subteam, engineering and deploying SVM, K-Nearest Neighbor, and YOLOv8 CNN models, achieving a 95\% accuracy in classifying microscopic 3D print images into defective and non-defective categories.

- Employed feature extraction techniques including Histogram of Oriented Gradients (HOG), enhancing model performance and reducing false negatives by $20 \%$, critical for early defect detection.

- Conducted rigorous iterative testing, model tuning, and data augmentation strategies, improving classification accuracy by $15 \%$, significantly elevating the quality control standards in $3 \mathrm{D}$ printing processes.

PROJECTS

\section*{CryptoLearn}

- Developed a live crypto and stocks tracker using Binance and Yahoo Finance APIs, providing real-time data on prices across $10+$ currencies, tracking $200+$ daily trades, and monitoring $50+$ assets' market metrics.

- Created a financial dashboard with matplotlib and CryptoCompare API, analyzing 100+ cryptocurrencies' returns over various periods, and rendering data visualizations for enhanced investment insights.

\section*{DayMaker}

- Developed DayMaker, streamlining event and deadline tracking by processing uploaded documents with OCR and NLP, and syncing extracted dates to Google Calendar, automating 500+ event entries.

- Implemented secure authentication and authorization for Google Calendar and NLP Google Cloud APIs access, enhancing system security.

- Orchestrated OAuth 2.0 Protocol for secure Google Calendar API requests, ensuring accurate data synchronization.

- Achieved 1st place in the Google Cloud Category at HackTX hackathon.

LEADERSHIP

Undegraduate Research Ambassadors

Computer Science Research Ambassador

August 2023 - Present

Atlanta, Georgia

- Spearheaded undergraduate research initiatives, boosting engagement by $30 \%$ with the involvement of over 200 students.

- Offered personalized guidance through one-on-one sessions with $50+$ freshmen and sophomores, aiding their integration into $20+$ ongoing research projects.

Bahrain Crown Prince International Scholarship Program Alumni Association $\quad$ Jul 2021 - Present Academic Mentor

- Mentored 30+ candidates in the Crown Prince International Scholarship Program (CPISP), aiding in their academic and career advancements.

- Conducted 50+ individual remote consultations, providing tailored advice and fostering a supportive environment.