\title{
Nabeel Hossain
}

\author{
+1701-740-0406nhossain34@gatech.edu linkedin.com/in/nabeel-hossain
}

Education

Georgia Institute of Technology

Expected May 2025

Master of Science in Computer Science, Machine Learning

Georgia Institute of Technology

Expected May 2024

Bachelor of Science in Computer Science, Intelligence and System Architecture

GPA: 4.0

\section*{Experience}

Teaching Assistant, Georgia Tech College of Computing - Atlanta, GA

- Debugged and graded assignments in C using GDB. Provided comprehensive feedback to significantly enhance students' understanding of systems level programming and problem solving strategy.

- Facilitated lab sessions to review and answer questions on fundamental course topics using slides, example problems, and hands on demonstrations to over 40 students weekly.

- Provided exceptional support and guidance to students in-person, virtually, and via discussion forums, promptly addressing their questions and concerns to create a highly conducive learning environment.

- Improved efficiency in debugging, testing, and grading by a factor of 5 using python and Linux shell tools.

Bits of Good, Georgia Tech College of Computing - Atlanta, GA

Sept 2022 - Present

- Developed, performed code reviews, and organized technical leadership for nonprofit development

- Collaborated within a 9-member agile team structure, working closely with an Engineering Manager, a Product Manager, and a team of 4 developers to deliver high-quality projects

- Directed project development by creating sprint tickets, prioritizing tasks and ensuring timely progress

- Demonstrated strong technical expertise by reviewing pull requests, providing constructive feedback to fellow developers, and resolving merge conflicts promptly and effectively

Projects

Customer Churn Prediction

- Predictive model for judging attrition rates for credit card customers given various features

May 2023 - July 2023

- Collaborated with and coordinated tasks on 5-person team; utilized popular python data science and visualization libraries, such as NumPy, Pandas, PyPlot, and SKLearn

- Conducted thorough data exploration, feature selection, and class balancing on dataset of 10,000 customers

- Achieved 0.96 weighted f-1, 0.90 minority class recall after rigorous, documented model tuning and selection.

Earthcraft

Sept 2022 - Apr 2023

- Developed a NextJS 12 application backed by MongoDB and Azure Blob Storage, efficiently organizing a digital library of over 1,000 sustainable building standards to be taggable, searchable

- Implemented a comprehensive solution for creating, searching, organizing, editing, and sharing standards, enabling clients to organize their information 3 times faster than before

- Designed the innovative Report Builder Feature, allowing engineers to seamlessly generate project reports by combining multiple standards, images, and user notes. Accelerated productivity with one-link PDF sharing.

- Utilized SWR for responsive UI updates and Server-Side Rendering for optimized loading speed.

CleanUpCrew

Apr 2020 - June 2020

- Developed a dynamic decentralized crowdfunding platform using NextJS, MongoDB, and Google Maps API.

- Used aggregated geospatial data to design and implement a unique algorithm that can identify posts with the greatest potential community impact to prioritize to viewers

- Crafted a sleek and responsive user interface, ensuring seamless user experience across various devices.

- Coordinated frontend and backend tasks within a lean team of four, successfully delivering the project within an impressive 36-hour timeframe.

Skills

Languages: Python, Java, JavaScript, TypeScript, C, C++, HTML/CSS

Frameworks: ReactJS, Node.js, Express.js, Next.js, Flask, SCSS, jQuery, Mongoose.js

Technologies: SQL, MongoDB, LATEX, NumPy, Matplotlib, Pandas, Git, Linux and Windows CLI

Coursework: Data Structures and Algorithms, Design and Analysis of Algorithms, Systems and Networks, Operating System Design, Machine Learning, Processor Design, Advanced Computer Organization