Bachelor's in Computer Science

Atlanta, GA

Courses: Data Structures \& Algos, Linear Algebra, Design \& Analysis of Algorithms, Computer Organiz \& Program, Objects $8 \mathcal{G}$ Design Certificates/Achievements: Deep Learning Specialization by DeepLearning.AI

Software Eng. Virtual Experience by J.P. Morgan (Forage)

Work Experience

Faculty Honors Award Spring 2022, Dean's List Fall 2022 \& Spring 2023

Accelerating Materials Discovery with AI

Undergraduate Researcher

August 2023 - Present

Atlanta, GA

- Applied graph neural networks to accelerate the discovery of next-generation catalysts, batteries, and solar cells, reducing time-to-discovery by $40 \%$ compared to traditional methods.

- Developed innovative data-driven algorithms for atomic-level inverse design with a goal of achieving chemical accuracy, resulting in a $20 \%$ improvement in model reliability through the incorporation of domain-specific physical constraints.

- Engineered a scalable testing platform integrated with big data analytics and data visualization capabilities, setting new benchmarks for materials discovery research.

Big Data Big Impact @ Georgia Tech

August 2022 - May 2023

Frontend Developer

Atlanta, GA

- Developed the front end of a web application to visualize data collected from neural network-based damage cost estimation of US hurricanes

- Created UI from scratch utilizing Figma and React, integrating Google API for a geo-mapping service to plot paths \& track the progress of hurricane patterns

- Developed interactive data visualizations using React and D3.js to display complex data in an easily understandable format, resulting in a boost in user engagement with the application

- Worked closely with the team to integrate the neural network model for estimating damage costs into the app, resulting in a $40 \%$ decrease in damage cost estimation time.

Georgia Tech Off-Road - Baja SAE

Jan 2022 - May 2022

Data Acquisition Engineer

Atlanta, GA

- Designed \& maintained data acquisition subsystem for efficient collection, storage \& manipulation of test data, critical to team's R\&D efforts and successfully resulting in yearly design improvements of up to $5 \%$

- Developed real-time system for the integration of collected and processed data yielding a $20 \%$ improvement in testing cycle times, delivering reliable insights into the car's design

- Enhanced continuous quality assurance framework that enabled daily validation/testing process \& improved accuracy by $70 \%$, paving the way for timely product releases

TransData

Web Developer

Aug 2021 - Dec 2021

- Created four engaging web applications for businesses, increasing user engagement and efficiency by $20 \%$

- Designed and developed UI/UX features with client feedback in mind, resulting in a $75 \%$ rise in customer ratings

- Utilized innovative strategies to increase application scalability and guarantee data security through Penetration Testing

Project Experience

Full Stack Threads App | Next.js, Clerk, Tailwind CSS, MongoDB, Shadcn, Figma, Zod

Jun 2023 - Present

- Designed an intuitive UI using Figma, Next.js, and Tailwind CSS, enhanced with custom shades via Shadcn.

- Engineered a secure user authentication and profile management system leveraging Clerk for robust backend functionality.

- Utilized MongoDB for data storage, accommodating complex schemas and efficient data population.

- Integrated UploadThing for file management and employed Zod for robust data validation, enhancing overall user experience.

Face Recognition System | TensorFlow

May 2023 - Jun 2023

- Implemented a high-performance ConvNet-based face verification and recognition system, utilizing FaceNet's state-of-the-art one-shot learning and triplet loss algorithms to compute 128-dimensional face encodings.

- Tuned model parameters to enhance prediction accuracy, achieving $98 \%$ precision and recall.

- Developed a verification mechanism that leverages L2 distance calculations to determine identity authenticity, ensuring secure access for verified individuals with an impressive accuracy threshold of 0.7.

- Applied Neural Style Transfer techniques to augment the capabilities of the face recognition system, providing not only identity verification but also real-time artistic rendering of detected faces.

\title{
Leadership Experience
}

Effective Altruism at Georgia Tech

Organizer

August 2023 - Present

Atlanta, GA

- Completed AI Safety Fundamentals Fellowship, culminating in a capstone, new approaches to Myopic Decision Theory

- Plan to develop updates to the AI Safety Fundamentals Fellowship, along with developing new materials to raise interest for it at Georgia Tech