\title{
TAWFIQ MOHAMMAD
}

\author{
$+1(770) 652-6679 \diamond$ Atlanta, GA \\ tawfiqfm@gmail.com $\diamond$ LinkedIn $\diamond$ tawfiqmohammad.me
}

\section*{EDUCATION}

Georgia Institute of Technology

Major: B.S. in Computer Science, GPA: 3.87/4.0,

August 2020 - December 2023

Relevant Coursework: Computer Networks, Data Structures and Algorithms, Deep Learning, Compilers, Robotics, High-Performance Computer Architecture, Operating Systems, Advanced Algorithms, Processor Design

TECHNICAL SKILLS AND ADDITIONAL INFORMATION

Technical Skills: Java, JavaScript, ReactNative, Go, Python, Django, SQL, Flutter, C/C++, Assembly

Languages: $\quad$ English (native), Arabic (fluent), Spanish (intermediate)

\section*{EXPERIENCE}

Google

May 2023 - Aug 2023

Software Engineer Intern

New York, NY

- Led the development and successful launch of a user-friendly star rating smart chip for Google Sheets, now available to millions of users.

- Utilized my expertise in Java and Javascript to discuss and formulate the design and implementation approach of the smart chip

- Participated in quality assurance testing for the smart chip, incorporating feedback to optimize its behavior and functionality

Google

May 2022 - Aug 2022

Software Engineer Intern

Seattle, WA

- Conceived and implemented a robust deployment completion classification procedure involving the cleaning and processing of over two years worth of deployment data using intricate SQL queries

- Developed deployment completion projection formulas and calculated projections using Go

- Led the design and implementation of a dynamic and interactive visualization dashboard using HTML, CSS, and JavaScript, serving as a key tool for over 100 users monthly

Georgia Tech Stadium-IoPT

Aug 2021 - Jan 2023

Machine Learning Engineer

Atlanta, GA

- Collaborating with a cross-functional team of two engineers and a project manager to develop a cutting-edge football play classifier using spatio-temporal analysis techniques

- Utilizing Python and Tensorflow for advanced data processing, modeling, and analysis, thereby creating a football play classifier with $\mathbf{8 3 \%}$ accuracy

\section*{PROJECTS}

\section*{SustAIn: Hackathon Project}

- Built a social media platform to promote sustainable habits using Django, SQLite, Bootstrap, and GPT-3.5.

- Users can create and join challenges made by GPT-3.5, track their progress on a map, and see their friends' completed challenges on the feed

\section*{Compiler Design}

- Designed and developed a Compiler in Python that performs static analysis and code optimization of Tiger-IR

- Uses optimization techniques such as redundancy elimination, instruction scheduling, and register allocation

- Performs MIPS32 code generation from Tiger-IR and control-flow analysis based on LLVM