Zaeem Ahmad

C: 916-300-3117, E: Zahmad34@gatech.edu

Nationality: USA

EDUCATION

$2021-2025$

Georgia Institute of technology

BS, Major: Computer Science

Atlanta, Georgia

$2017-2020$

California Virtual Academy @ Sutter

EXPERIENCE

Honors: Dean's Honor List for 4 consecutive semesters; CGPA 3.96 / 4.00

Roseville, California

Aug'23-Present VIP Undergraduate Researcher, Georgia Institute of Technology

Atlanta, Georgia

- Developed a robust object-oriented programming (OOP) framework with multiple classes and instance methods for substation component modeling, enhancing flexibility and scalability.

- Integrated communication protocols to ensure seamless data exchange among diverse components, leading to improved efficiency within smart grid systems.

- Conducted comprehensive research on component variables, providing valuable insights that significantly improved the accuracy of co-simulation models and informed data-driven decision-making.

- Implemented co-simulation using the HELICS framework, ensuring accurate representation and interaction of components, thus contributing to the project's overall success.

May'23-Present Undergraduate Researcher, Georgia Institute of Technology

Atlanta, Georgia

- Developed and implemented advanced Python-based computational models for cardiac electrophysiology, leading to a $30 \%$ improvement in arrhythmia understanding compared to existing models.

- Successfully translated complex MATLAB algorithms to Python, resulting in a $20 \%$ reduction in computation time while maintaining accuracy and reliability.

- Integrated high-throughput patch clamp data into the computational models to enhance parameter estimation precision.

- Collaborated in the creation of a novel hybrid algorithm, reducing the need for initial assumptions in parameter estimation by $40 \%$, thus significantly enhancing accuracy.

Jan'23-Aug'23 Big Data Big Impact CS Intern, Georgia Institute of Technology Atlanta, Georgia

- Spearheaded a cross-functional team effort to design and develop the Hurricane Cost Projector, a cutting-edge disaster impact prediction tool.

- Employed HTML, CSS, Python, and JavaScript to craft an intuitive and visually appealing front-end interface, ensuring a user-friendly and engaging experience.

- Enhanced the tool's effectiveness through the implementation of data visualization features, facilitating customer comprehension and interaction.

- Thrived in a dynamic, fast-paced environment, collaborating seamlessly within cross-functional teams to deliver impactful and innovative solutions to drive project success.

May'22-Aug'23 BluEast - Technical Intern

Lahore, Pakistan

- Assisted with PCB design \& embedded programming of an iOS \& Android compatible App, "Autopilot", that is built using JavaScript (Frontend \& Backend frameworks), Python, Ruby, PHP, \& C++

- Spearheaded optimization process for algorithm that employs Mevris AI to tweak thermostat of DC inverter air conditioner based on metrics to ensure thermal comfort \& reduce energy consumption by $80 \%$

- Developed an automation scheme for test condition parameters that saved configuration time on the system $\&$ resulted in an overall $50 \%$ reduction in validation testing time.

Sep'20-Aug'21 Orient Group of Companies - Business Analyst

Lahore, Pakistan

- Digitized sales network through 'Orient Dost' app that enabled $76+$ team members \& 100+ distributors spread across 16 territories to track performance in real time which led to a $20 \%$ increase in sales.

- Automated dispenser production line to enhance efficiency \& replaced steel tanks with aluminum to improve hygienic standards, reduce production cost by $4 \%$, \& achieve $100 \%$ annualized increase in sales .

- Led team of 4 to implement employment 'Training Need Program' in SAP ERP to improve productivity of 67 middle management employees who completed 6 different training programs as part of this initiative.

\title{
EXTRA-CURRICULAR
}

- National Champion at National Tournament of Young Math, National STEM Educational Foundation Tournament of Young Mathematicians 2019.

- Contestant at International Earth Science Olympiad (2020 event canceled due to COVID-19).

- National Champion at National Earth Science Olympiad, National STEM Educational Foundation 2019-2020.

SKILLS

- Programming Languages - C++, Python, Java, JavaScript, HTML, React.JS, React Native, MATLAB, CSS, Figma, GitHub, Git

- $\quad$ Languages - English (Fluent), Urdu (Native), Hindi (Fluent), Punjabi (Intermediate)